name: Docker-image-real-time-automatic-attendance-system

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install CMake
        run: sudo apt install cmake

      - name: Build the Docker image
        run: docker build -t real-time-automatic-attendance-system:latest .

      - name: Push the Docker image
        run: docker push real-time-automatic-attendance-system:latest
