name: Build ML Model with DVC

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESSKEYID }}
        aws-secret-access-key: ${{ secrets.ACCESSKEY }}
        aws-region: us-east-1
    
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    
    - name: Install dependencies
      run: pip install -r requirements.txt
    
        
    - name: Pull data with DVC
      run: dvc pull
    
    - name:  DVC pipeline
      run: dvc repro 
